/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import java.lang.reflect.InvocationTargetException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Listas.ListaConsumo;
import model.Objetos.Consumo;


/**
 *
 * @author Ketrin D. Vargas, Marina B. Otokovieski, Rafael Souza
 */
public class Contabilidade extends javax.swing.JInternalFrame {

    /**
     * Creates new form Contabilidade
     */
    private static List<Consumo> listaConsumo;
    private static int[] indexRg;
    private DefaultTableModel dtm;
    public Contabilidade(ListaConsumo listaConsumo) {
        initComponents();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jRGBuscaConsumo = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabConsumoCliente = new javax.swing.JTable();
        jBotaoPagarConsumo = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jCodConsumo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jRGClienteConsumo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jCodProdConsumo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jQtdProdConsumo = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setClosable(true);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Consumo Cliente");

        jLabel7.setText("RG do Cliente");

        jButton2.setText("Pesquisar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTabConsumoCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Entrada", "Produto", "Quantidade", "Preço Unitário", "Preço Total", "Total do Consumo "
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTabConsumoCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabConsumoClienteMouseClicked(evt);
            }
        });
        jTabConsumoCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTabConsumoClienteKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTabConsumoCliente);

        jBotaoPagarConsumo.setText("Pagar");
        jBotaoPagarConsumo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotaoPagarConsumoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRGBuscaConsumo, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton2))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(255, 255, 255)
                                .addComponent(jLabel6)))
                        .addGap(0, 130, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBotaoPagarConsumo, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jRGBuscaConsumo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBotaoPagarConsumo)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Consumo Cliente", jPanel2);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Novo Consumo");

        jLabel2.setText("Código do consumo");

        jCodConsumo.setEditable(false);

        jLabel3.setText("RG Cliente");

        jLabel4.setText("Código do Produto");

        jLabel5.setText("Quantidade");

        jButton1.setText("Confirma");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCodConsumo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRGClienteConsumo, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jQtdProdConsumo)
                            .addComponent(jCodProdConsumo))))
                .addGap(170, 170, 170))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(278, 278, 278))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(259, 259, 259))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCodConsumo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRGClienteConsumo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCodProdConsumo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jQtdProdConsumo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(47, 47, 47)
                .addComponent(jButton1)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Novo Consumo", jPanel1);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Custo e Lucro");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Custo ", "Lucro Gerado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(279, 279, 279)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 671, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Caixa", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (jCodConsumo.getText().equals("") || jRGClienteConsumo.getText().equals("")||
          jCodProdConsumo.getText().equals("")|| jQtdProdConsumo.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Informe todos os campos!");
      } else {
          Consumo cons = new Consumo(
                  Integer.parseInt(jRGClienteConsumo.getText().trim()),
                  Boolean.getBoolean(jQtdProdConsumo.getText().trim()));
        
            try {
                if (ListaConsumo.addConsumo(cons) == false) {
                    JOptionPane.showMessageDialog(null, "Não foi possível salvar.");
                } else {
                    JOptionPane.showMessageDialog(null, "Cadastro Efetuado!");
                    Object obj = null;
                    dtm.addRow((Object[]) obj);
                    ListaConsumo.inicia();
                    limpar();  
                }
            } catch (Exception ex) {
                Logger.getLogger(Contabilidade.class.getName()).log(Level.SEVERE, null, ex);
            }

        }      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try {
            int i = Integer.parseInt(jRGBuscaConsumo.getText());
            ListaConsumo.consultarConsumo(i);
            listaConsumo();           
        } catch (Exception ex) {
            Logger.getLogger(AreaCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jBotaoPagarConsumoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotaoPagarConsumoActionPerformed
        // TODO add your handling code here:
 
        int index = jTabConsumoCliente.getSelectedRow();
        int rg = getRg(index);
       
        try {
            if (ListaConsumo.pagarConsumo(rg)) {
                JOptionPane.showMessageDialog(null, "Campo não encontro");
            } else {
                ListaConsumo.inicia();
                
                DefaultTableModel dtm = (DefaultTableModel) jTabConsumoCliente.getModel();
                dtm.removeRow(jTabConsumoCliente.getSelectedRow());
                JOptionPane.showMessageDialog(null, "Campo deletado com sucesso.");
            }
        } catch (Exception ex) {
            Logger.getLogger(Contabilidade.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }//GEN-LAST:event_jBotaoPagarConsumoActionPerformed

    private void jTabConsumoClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabConsumoClienteMouseClicked
        // TODO add your handling code here:
        
        if(jTabConsumoCliente.getSelectedRow() != -1){
            
          jCodConsumo.setText(jTabConsumoCliente.getValueAt(jTabConsumoCliente.getSelectedRow(), 0).toString());
          jRGClienteConsumo.setText(jTabConsumoCliente.getValueAt(jTabConsumoCliente.getSelectedRow(), 1).toString());
          jCodProdConsumo.setText(jTabConsumoCliente.getValueAt(jTabConsumoCliente.getSelectedRow(), 2).toString());
          jQtdProdConsumo.setText(jTabConsumoCliente.getValueAt(jTabConsumoCliente.getSelectedRow(), 3).toString());
    
        }
    }//GEN-LAST:event_jTabConsumoClienteMouseClicked

    private void jTabConsumoClienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTabConsumoClienteKeyReleased
        // TODO add your handling code here:
        
        if(jTabConsumoCliente.getSelectedRow() != -1){
            
          jCodConsumo.setText(jTabConsumoCliente.getValueAt(jTabConsumoCliente.getSelectedRow(), 0).toString());
          jRGClienteConsumo.setText(jTabConsumoCliente.getValueAt(jTabConsumoCliente.getSelectedRow(), 1).toString());
          jCodProdConsumo.setText(jTabConsumoCliente.getValueAt(jTabConsumoCliente.getSelectedRow(), 2).toString());
           jQtdProdConsumo.setText(jTabConsumoCliente.getValueAt(jTabConsumoCliente.getSelectedRow(), 3).toString());
    
        }
    }//GEN-LAST:event_jTabConsumoClienteKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBotaoPagarConsumo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JTextField jCodConsumo;
    private javax.swing.JTextField jCodProdConsumo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jQtdProdConsumo;
    private javax.swing.JTextField jRGBuscaConsumo;
    private javax.swing.JTextField jRGClienteConsumo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTabConsumoCliente;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
 private void limpar() {
      jCodConsumo.equals("");
      jRGClienteConsumo.equals("");
      jCodProdConsumo.equals("");
      jQtdProdConsumo.equals("");
 }
   public static int getRg(int index){
        return indexRg[index];
    }
   
    public void listaConsumo() throws IllegalAccessException, IllegalArgumentException, InvocationTargetException{
        Consumo objetoConsumo =  new Consumo(0, false);
        dtm = (DefaultTableModel) jTabConsumoCliente.getModel();
        listaConsumo = ListaConsumo.getLista(objetoConsumo, null, null);

        for (int i = 0; i<listaConsumo.size(); i++){
            Consumo con = listaConsumo.get(i);
            indexRg[i++] = con.getCod(); 
        }

        int indexador = 0;
        for (Consumo m : listaConsumo){
            jTabConsumoCliente.setValueAt(m.getCod(), indexador, 0);
            jTabConsumoCliente.setValueAt(m.getRg(), indexador, 1);
            jTabConsumoCliente.setValueAt(m.getCod(), indexador, 2);
            jTabConsumoCliente.setValueAt(m.getProdutoQuantidade(), indexador, 3);
            indexador++;
        }
   }
 }
