/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import javax.swing.JOptionPane;

/**
 *
 * @author marin
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jBotaoConfirmaTelaInicial = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jAreaClienteBarraSuperior = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jAreaProdutosBarraSuperior = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jCaixaBarraSuperiorTelaPrincipal = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jSobre = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jComoUsarTelaPrincipal = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\marin\\Downloads\\Confraria (1) (3).png")); // NOI18N

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Selecione o item desejado>", "Área de Clientes", "Área de Produtos", "Administração" }));

        jBotaoConfirmaTelaInicial.setText("Confirma");
        jBotaoConfirmaTelaInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotaoConfirmaTelaInicialActionPerformed(evt);
            }
        });

        jDesktopPane2.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jComboBox1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jBotaoConfirmaTelaInicial, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(169, 169, 169))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane2Layout.createSequentialGroup()
                        .addComponent(jBotaoConfirmaTelaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(198, 198, 198))))
            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 126, Short.MAX_VALUE))
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBotaoConfirmaTelaInicial)
                .addContainerGap(111, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane2)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane2)
        );

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/user.png"))); // NOI18N
        jMenu1.setText("Clientes");

        jAreaClienteBarraSuperior.setText("Área do Cliente");
        jAreaClienteBarraSuperior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAreaClienteBarraSuperiorActionPerformed(evt);
            }
        });
        jMenu1.add(jAreaClienteBarraSuperior);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cart.png"))); // NOI18N
        jMenu2.setText("Produtos");

        jAreaProdutosBarraSuperior.setText("Área de Produtos");
        jAreaProdutosBarraSuperior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAreaProdutosBarraSuperiorActionPerformed(evt);
            }
        });
        jMenu2.add(jAreaProdutosBarraSuperior);

        jMenuBar1.add(jMenu2);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/money_dollar.png"))); // NOI18N
        jMenu5.setText("Financeiro");

        jCaixaBarraSuperiorTelaPrincipal.setText("Caixa");
        jCaixaBarraSuperiorTelaPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCaixaBarraSuperiorTelaPrincipalActionPerformed(evt);
            }
        });
        jMenu5.add(jCaixaBarraSuperiorTelaPrincipal);

        jMenuBar1.add(jMenu5);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/information.png"))); // NOI18N
        jMenu3.setText("Sobre");

        jSobre.setText("Sobre o sistema");
        jMenu3.add(jSobre);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Ajuda");

        jComoUsarTelaPrincipal.setText("Como Usar");
        jComoUsarTelaPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComoUsarTelaPrincipalActionPerformed(evt);
            }
        });
        jMenu4.add(jComoUsarTelaPrincipal);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jComoUsarTelaPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComoUsarTelaPrincipalActionPerformed
        JOptionPane.showMessageDialog(jMenuBar1, "Clientes: A área de administração de clientes pode ser acessada através da caixa"
                + "de seleção na tela inicial e através do menu superior Clientes\n"
                + "Produtos: A área de administração de produtos pode ser acessada através da caixa"
                + "de seleção na tela inicial e através do menu superior Produtos\n"
                + "Financeiro: a área de contabilidade e controle de caixa pode ser acessada"
                + "através da caixa de seleção na tela inicial e através do menu superior Financeiro");
    }//GEN-LAST:event_jComoUsarTelaPrincipalActionPerformed

    private void jBotaoConfirmaTelaInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotaoConfirmaTelaInicialActionPerformed
        String indice = jComboBox1.getSelectedItem().toString();
        switch (indice) {
            case "Área de Clientes":
                AreaCliente Clientess = new AreaCliente();
                jDesktopPane2.add(Clientess);
                Clientess.setVisible(true);

                break;
            case "Área de Produtos":
                AreaProdutos Produtoss = new AreaProdutos();
                jDesktopPane2.add(Produtoss);
                Produtoss.setVisible(true);

                break;
            case "Administração":
                Contabilidade Adm = new Contabilidade();
                jDesktopPane2.add(Adm);
                Adm.setVisible(true);

                break;
        }
    }//GEN-LAST:event_jBotaoConfirmaTelaInicialActionPerformed

    private void jAreaClienteBarraSuperiorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAreaClienteBarraSuperiorActionPerformed
        AreaCliente Clientess = new AreaCliente();
        jDesktopPane2.add(Clientess);
        Clientess.setVisible(true);
    }//GEN-LAST:event_jAreaClienteBarraSuperiorActionPerformed

    private void jAreaProdutosBarraSuperiorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAreaProdutosBarraSuperiorActionPerformed
        AreaProdutos Produtoss = new AreaProdutos();
        jDesktopPane2.add(Produtoss);
        Produtoss.setVisible(true);
    }//GEN-LAST:event_jAreaProdutosBarraSuperiorActionPerformed

    private void jCaixaBarraSuperiorTelaPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCaixaBarraSuperiorTelaPrincipalActionPerformed
        Contabilidade Adm = new Contabilidade();
        jDesktopPane2.add(Adm);
        Adm.setVisible(true);
    }//GEN-LAST:event_jCaixaBarraSuperiorTelaPrincipalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jAreaClienteBarraSuperior;
    private javax.swing.JMenuItem jAreaProdutosBarraSuperior;
    private javax.swing.JButton jBotaoConfirmaTelaInicial;
    private javax.swing.JMenuItem jCaixaBarraSuperiorTelaPrincipal;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JMenuItem jComoUsarTelaPrincipal;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JMenuItem jSobre;
    // End of variables declaration//GEN-END:variables
}
